# Generated by Django 4.0.3 on 2022-04-03 12:02

from django.db import migrations, models

try:
    # Try to import GeoDjango field; this can fail when GDAL isn't installed.
    import django.contrib.gis.db.models.fields as gis_fields
except Exception:
    gis_fields = None


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220105_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=(gis_fields.PointField(blank=True, null=True, srid=4326) if gis_fields else models.CharField(max_length=100, blank=True, null=True)),
        ),
    ]
